Repository WildCodeSchool/orleans-php-202009-project-coachsportif, pull requests merged in 2021-01, with the labels that each got.

#76 S01 us04 creation formulaire contact
  assets/images/SalleSport.jpg
  assets/images/favicon.jpg
  assets/images/salleSport.jpg
  assets/js/app.js
  assets/styles/home.scss
  assets/styles/homeCo.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/packages/translation.yaml
  config/services.yaml
  src/Controller/HomeController.php
  src/Entity/ContactHome.php
  src/Form/ContactHomeType.php
  templates/contact/contactConfirmation.html.twig
  templates/home/contactHomeEmail.html.twig
  templates/home/index.html.twig
  templates/include/_navbar.html.twig
  webpack.config.js
Labels: Reviewed

#85 fixed some issues
  assets/images/SalleSport.jpg
  assets/styles/fitness.scss
  migrations/Version20201216140300.php
  src/Controller/FitnessController.php
  src/Entity/Fitness.php
  src/Form/FitnessType.php
  src/Repository/FitnessRepository.php
  templates/fitness/_delete_form.html.twig
  templates/fitness/_form.html.twig
  templates/fitness/edit.html.twig
  templates/fitness/index.html.twig
  templates/fitness/indexAdmin.html.twig
  templates/fitness/new.html.twig
  templates/fitness/show.html.twig
Labels: Reviewed

#68 S02 us50 carrousel
  assets/images/nordic_walking_place_holder_2.jpg
  assets/images/placeholder.png
  assets/images/placeholder150.png
  assets/images/placeholder2.png
  assets/images/placeholder3.png
  assets/images/remise_en_forme_carousel.jpg
  assets/images/remise_en_forme_carousel_2.jpg
  assets/styles/app.scss
  assets/styles/fitness.scss
  assets/styles/walking.scss
  migrations/Version20201217093853.php
  migrations/Version20201223150555.php
  src/Controller/FitnessController.php
  src/Controller/HomeController.php
  src/Controller/WalkingController.php
  src/DataFixtures/CarouselFixtures.php
  src/DataFixtures/HomeFixture.php
  src/DataFixtures/HomeFixtures.php
  src/Entity/Carousel.php
  src/Entity/Home.php
  src/Repository/CarouselRepository.php
  templates/base.html.twig
  templates/fitness/index.html.twig
  templates/home/index.html.twig
  templates/include/_carousel.html.twig
  templates/include/_navbar.html.twig
  templates/layout.html.twig
  templates/walking/show.html.twig
Labels: Reviewed

#86 S04 us40 admin delete home
  src/Controller/FitnessController.php
  templates/home/_delete_form.html.twig
Labels: Reviewed

#88 Us36 admin edit opinion
  src/Controller/OpinionController.php
  templates/opinion/edit.html.twig
Labels: Reviewed

#93 Us35 admin add opinion
  src/Controller/OpinionController.php
  templates/opinion/new.html.twig
Labels: Reviewed

#94 Us37 admin deleted opinion
  src/Controller/OpinionController.php
  templates/opinion/_delete_form.html.twig
Labels: Reviewed

#92 S04 us45 create add form admin walking
  assets/styles/adminWalking.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210106093800.php
  public/uploads/dance-3134828_640.jpg
  src/Entity/Walking.php
  src/Form/WalkingType.php
  symfony.lock
  templates/home/index.html.twig
  templates/walking/_delete_form.html.twig
  templates/walking/_form.html.twig
  templates/walking/admin.html.twig
  templates/walking/index.html.twig
  templates/walking/new.html.twig
Labels: Reviewed

#99 creation entity tarif
  migrations/Version20210106130622.php
  src/Controller/AdminTariffController.php
  src/Entity/Tariff.php
  src/Form/TariffType.php
  src/Repository/TariffRepository.php
  templates/admin/tarif/_form.html.twig
  templates/admin/tarif/index.html.twig
  templates/admin/tarif/new.html.twig
Labels: Reviewed

#97 S04 us50 carrousel upload
  assets/images/placeWalking.png
  assets/images/placefitness.png
  composer.lock
  config/packages/vich_uploader.yaml
  migrations/Version20201223150555.php
  migrations/Version20210106135228.php
  src/Controller/CarouselController.php
  src/DataFixtures/CarouselFixtures.php
  src/Form/CarouselType.php
  templates/carousel/_delete_form.html.twig
  templates/carousel/_form.html.twig
  templates/carousel/edit.html.twig
  templates/carousel/index.html.twig
  templates/carousel/new.html.twig
  templates/carousel/show.html.twig
Labels: Reviewed

#87 Us19 form contact
  assets/images/SalleSport.jpg
  assets/styles/contact.scss
  composer.lock
  src/Controller/ContactController.php
  src/Controller/FitnessController.php
  templates/contact/contact.html.twig
  webpack.config.js
Labels: Reviewed

#102 S04 us01 remise en forme fix3
  composer.lock
  migrations/Version20210106093800.php
  migrations/Version20210106132408.php
  migrations/Version20210106135228.php
  migrations/Version20210107091140.php
  src/DataFixtures/FitnessFixtures.php
  templates/home/index.html.twig
Labels: Reviewed

#104 S01 us04 creation formulaire contact
  templates/home/index.html.twig
Labels: Reviewed

#100 S04 us50 carrousel upload
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210106143444.php
  public/uploads/path/140x100.png
  public/uploads/walking/dance-3134828_640.jpg
  src/Entity/Carousel.php
  src/Form/CarouselType.php
  templates/carousel/new.html.twig
Labels: Reviewed

#110 modified Add text fitness
  src/Controller/FitnessController.php
  src/Form/FitnessType.php
  templates/fitness/_form.html.twig
  templates/fitness/new.html.twig
Labels: Reviewed

#108 ajout upload home
  composer.lock
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210106143444.php
  migrations/Version20210107091140.php
  public/uploads/DamienG.jpg
  src/Controller/HomeController.php
  src/Entity/Home.php
  src/Form/HomeType.php
  templates/home/_delete_form.html.twig
  templates/home/edit.html.twig
  templates/home/index_admin.html.twig
  templates/home/show.html.twig
Labels: Reviewed

#117 ajout demande client
  templates/include/_navbar.html.twig
Labels: Reviewed

#118 S04 us49 barre navigation admin
  templates/includeAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#119 message flash
  src/Controller/HomeController.php
Labels: Reviewed

#115 flash message
  public/uploads/path/LosingWeight.jpg
  public/uploads/path/fondSectionSport.jpg
  public/uploads/path/nordic_walking_place_holder_1.jpg
  public/uploads/path/overlay.jpg
  src/Controller/CarouselController.php
  templates/base.html.twig
Labels: Reviewed

#111 Us48 modifier tarif
  composer.lock
  src/Controller/AdminTariffController.php
  templates/admin/tarif/_form.html.twig
  templates/admin/tarif/edit.html.twig
  templates/admin/tarif/index.html.twig
Labels: Reviewed

#138 Fix bug bar nav contact
  templates/base.html.twig
  templates/contact/contact.html.twig
  templates/include/_map.html.twig
Labels: Reviewed

#140 S05 us38 creation page tarif
  assets/js/app.js
  assets/styles/tariff.scss
  src/Controller/TariffController.php
  templates/contact/contact.html.twig
  templates/home/edit.html.twig
  templates/home/show.html.twig
  templates/include/_carousel.html.twig
  templates/include/_navbar.html.twig
  templates/tarif/index.html.twig
  webpack.config.js
Labels: Reviewed

#141 fixture tarifs
  src/DataFixtures/TariffFixtures.php
Labels: Reviewed

#145 fix input
  assets/styles/home.scss
  templates/home/edit.html.twig
Labels: Reviewed

#147 index commentaire
  src/Controller/OpinionController.php
  templates/opinion/index.html.twig
Labels: Reviewed

#149 fix edit opinion
  templates/opinion/_form.html.twig
  templates/opinion/edit.html.twig
Labels: Reviewed

#144 mise en place page admin index
  assets/images/carrouselAdmin.png
  assets/images/compteClient.png
  assets/images/logoAccueil.png
  assets/images/logoFitness.png
  assets/images/marcheNordique.png
  assets/images/media.png
  assets/images/presentation.png
  assets/images/salleSport.png
  assets/images/sportAdapter.png
  assets/images/sportTravail.png
  assets/images/tariff.png
  assets/js/app.js
  assets/styles/admin.scss
  src/Controller/AdminController.php
  templates/admin/index.html.twig
  templates/layout_admin.html.twig
  webpack.config.js
Labels: Reviewed

#150 fix new opinion
  templates/opinion/new.html.twig
Labels: Reviewed

#151 change color
  templates/includeAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#134 changement demande client couleur et photo
  assets/images/DamienG.jpg
  assets/images/FitnessCard.jpg
  assets/images/IMG_4510-compressed.jpg
  assets/images/salleSportContact.jpg
  assets/images/sportAdapteCard.jpg
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/include/_navbar.html.twig
Labels: Reviewed

#148 refonte show opinion
  assets/js/app.js
  assets/styles/adminOpinion.scss
  src/Controller/OpinionController.php
  templates/opinion/show.html.twig
  webpack.config.js
Labels: Reviewed

#155 US44 delete
  src/Controller/FitnessController.php
  templates/admin/fitness/_delete_form.html.twig
  templates/fitness/_delete_form.html.twig
Labels: Reviewed

#146 remise en forme de tout les boutons admin
  templates/carousel/_delete_form.html.twig
  templates/carousel/_form.html.twig
  templates/carousel/edit.html.twig
  templates/carousel/index.html.twig
  templates/carousel/new.html.twig
  templates/carousel/show.html.twig
  templates/home/_delete_form.html.twig
  templates/home/_form.html.twig
  templates/home/index_admin.html.twig
  templates/home/show.html.twig
  templates/opinion/_delete_form.html.twig
  templates/opinion/edit.html.twig
  templates/opinion/new.html.twig
  templates/walking/_delete_form.html.twig
  templates/walking/_form.html.twig
  templates/walking/edit.html.twig
  templates/walking/index.html.twig
  templates/walking/new.html.twig
  templates/walking/show.html.twig
Labels: Reviewed

#156 US43 modifier text
  src/Controller/FitnessController.php
  templates/admin/fitness/edit.html.twig
  templates/fitness/edit.html.twig
Labels: Reviewed

#98 S04 us12 session
  composer.lock
  config/packages/security.yaml
  config/packages/vich_uploader.yaml
  phpstan.neon
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  templates/include/_navbar.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#105 create edit form
  public/uploads/.gitignore
  src/Controller/WalkingController.php
  src/Entity/Walking.php
  templates/walking/admin.html.twig
  templates/walking/edit.html.twig
  templates/walking/show.html.twig
Labels: Reviewed

#157 fixed indexAdmin
  templates/admin/fitness/_form.html.twig
  templates/admin/fitness/indexAdmin.html.twig
  templates/admin/fitness/new.html.twig
  templates/admin/fitness/show.html.twig
  templates/fitness/_form.html.twig
  templates/fitness/indexAdmin.html.twig
  templates/fitness/show.html.twig
Labels: Reviewed

#112 Us49 suppress tariff
  composer.lock
  src/Controller/AdminTariffController.php
  templates/admin/tarif/_delete_form.html.twig
  templates/admin/tarif/index.html.twig
  templates/admin/tarif/new.html.twig
  templates/contact/contact.html.twig
Labels: Reviewed

#161 fix orthographe
  templates/admin/index.html.twig
Labels: Reviewed

#163 fix link barre navigation
  templates/include/_navbar.html.twig
Labels: Reviewed

#164 fix contact
  templates/contact/contact.html.twig
Labels: Reviewed

#158 creation de la page media
  migrations/Version20210112163540.php
  src/Controller/MediaController.php
  src/DataFixtures/MediaFixtures.php
  src/Entity/Media.php
  src/Repository/MediaRepository.php
  templates/media/index.html.twig
Labels: Reviewed

#165 Fix vich uploader
  assets/images/dep57.xls
  composer.lock
  config/packages/vich_uploader.yaml
  src/Entity/Carousel.php
Labels: Reviewed

#167 Remise en forme marche nordique
  assets/styles/adminWalking.scss
  assets/styles/contact.scss
  assets/styles/walking.scss
  src/Controller/WalkingController.php
  templates/admin/fitness/new.html.twig
  templates/walking/_form.html.twig
  templates/walking/admin.html.twig
  templates/walking/edit.html.twig
  templates/walking/new.html.twig
Labels: Reviewed

#172 Refonte suite a demande client
  assets/styles/whoIAm.scss
  templates/whoIAm/index.html.twig
Labels: Reviewed

#174 S06 us01 remise en forme refonte
  assets/styles/fitness.scss
  assets/styles/variables.scss
  src/Controller/FitnessController.php
  src/DataFixtures/FitnessFixtures.php
  templates/fitness/index.html.twig
Labels: Reviewed

#176 ajout label css
  assets/styles/app.scss
Labels: Reviewed

#171 fix refonte graphique admin fitness
  assets/styles/admin.scss
  templates/admin/fitness/_delete_form.html.twig
  templates/admin/fitness/_form.html.twig
  templates/admin/fitness/edit.html.twig
  templates/admin/fitness/indexAdmin.html.twig
  templates/admin/fitness/new.html.twig
  templates/admin/fitness/show.html.twig
Labels: Reviewed

#173 S05 us38 carousel avis clients
  assets/styles/whoIAm.scss
  templates/whoIAm/index.html.twig
Labels: Reviewed

#177 ajout lien plus changement couleur titre
  templates/include/_navbar.html.twig
  templates/media/index.html.twig
Labels: Reviewed

#179 initialized gym page
  assets/styles/gym.scss
  migrations/Version20210112163540.php
  migrations/Version20210118162432.php
  src/Controller/GymController.php
  src/DataFixtures/GymFixtures.php
  src/Entity/Gym.php
  src/Repository/GymRepository.php
  templates/gym/index.html.twig
  webpack.config.js
Labels: Reviewed

#180 S05 us06 admin nw media
  src/Controller/AdminMediaController.php
  src/Form/MediaType.php
  templates/admin/media/_delete_form.html.twig
  templates/admin/media/_form.html.twig
  templates/admin/media/edit.html.twig
  templates/admin/media/index.html.twig
  templates/admin/media/new.html.twig
  templates/admin/media/show.html.twig
Labels: Reviewed

#181 fixed errors
  webpack.config.js
Labels: Reviewed

#184 bouton tarif admin
  templates/admin/tarif/index.html.twig
  webpack.config.js
Labels: Reviewed

#175 Mise a jour entity opinion
  src/Controller/ContactController.php
  src/Controller/FitnessController.php
  src/Controller/GymController.php
  src/Controller/HomeController.php
  src/Controller/WalkingController.php
  src/Controller/WhoIAmController.php
  src/Entity/Opinion.php
  src/Form/CarouselType.php
  src/Form/OpinionType.php
Labels: Reviewed

#182 create customer cards with crud
  assets/images/salleSport.jpg
  migrations/Version20210119144434.php
  src/Controller/ProfileController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Entity/Walking.php
  src/Form/UserType.php
  templates/include/_navbar.html.twig
  templates/opinion/show.html.twig
  templates/profile/_delete_form.html.twig
  templates/profile/_form.html.twig
  templates/profile/edit.html.twig
  templates/profile/index.html.twig
  templates/profile/show.html.twig
Labels: Reviewed

#190 Us7 page modification admin media
  src/Controller/AdminMediaController.php
  templates/admin/media/edit.html.twig
Labels: Reviewed

#191 Us8 supp page admin media
  src/Controller/AdminMediaController.php
  templates/admin/media/_delete_form.html.twig
Labels: Reviewed

#193 Admin home moove admin home
  src/Controller/AdminHomeController.php
  src/Controller/HomeController.php
  templates/admin/home/_delete_form.html.twig
  templates/admin/home/_form.html.twig
  templates/admin/home/edit.html.twig
  templates/admin/home/index_admin.html.twig
  templates/admin/home/show.html.twig
Labels: Reviewed

#194 Fix couleur lien bar nav admin
  templates/includeAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#195 move walking to admin repository
  public/uploads/walking/dance-3134828_640.jpg
  src/Controller/WalkingController.php
  templates/admin/walking/_delete_form.html.twig
  templates/admin/walking/_form.html.twig
  templates/admin/walking/edit.html.twig
  templates/admin/walking/index.html.twig
  templates/admin/walking/new.html.twig
  templates/walking/show.html.twig
Labels: Reviewed

#197 create customer accounts section
  src/Controller/CustomerController.php
  templates/admin/customerAccount/index.html.twig
  templates/admin/index.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#200 add edit customer cards
  assets/js/app.js
  assets/styles/profile.scss
  src/Form/UserType.php
  templates/profile/_delete_form.html.twig
  templates/profile/_form.html.twig
  templates/profile/edit.html.twig
  templates/profile/show.html.twig
  webpack.config.js
Labels: Reviewed

#201 refonte graphique admin opinion
  assets/styles/admin.scss
  src/Controller/OpinionController.php
  src/Form/OpinionType.php
  templates/opinion/_delete_form.html.twig
  templates/opinion/_form.html.twig
  templates/opinion/edit.html.twig
  templates/opinion/index.html.twig
  templates/opinion/new.html.twig
Labels: Reviewed

#202 Us58 new activity
  src/Controller/ActivityController.php
  src/Entity/Activity.php
  src/Form/ActivityType.php
  src/Repository/ActivityRepository.php
  src/Repository/CompanyRepository.php
  templates/admin/activity/_delete_form.html.twig
  templates/admin/activity/_form.html.twig
  templates/admin/activity/edit.html.twig
  templates/admin/activity/index.html.twig
  templates/admin/activity/new.html.twig
  templates/admin/activity/show.html.twig
Labels: Correction done

#208 modification index admin media
  templates/admin/media/index.html.twig
Labels: Reviewed

#209 add admin walking controller and change routes
  migrations/Version20210120085602.php
  migrations/Version20210120103016.php
  src/Controller/AdminWalkingController.php
  src/Controller/WalkingController.php
Labels: Reviewed

#210 changement nom de route
  src/Controller/AdminHomeController.php
Labels: Reviewed

#216 Us18 creation compte client
  composer.json
  composer.lock
  config/bundles.php
  phpstan.neon
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/base.html.twig
  templates/include/_navbar.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#217 fix Fitness admin and path
  src/Controller/AdminFitnessController.php
  src/Controller/FitnessController.php
  templates/admin/fitness/edit.html.twig
  templates/admin/fitness/new.html.twig
  templates/admin/index.html.twig
  templates/includeAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#218 ajout bouton
  config/packages/security.yaml
  templates/include/_navbar.html.twig
  templates/includeAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#223 add view profil from accounts
  templates/admin/customerAccount/index.html.twig
  templates/profile/show.html.twig
Labels: Reviewed

#226 fix edit button
  templates/admin/walking/index.html.twig
Labels: Reviewed

#220 erreur carrousel
  assets/styles/admin.scss
  templates/admin/index.html.twig
  templates/contact/contact.html.twig
Labels: Reviewed

#224 calendar + entité + crud + modification index(list)
  assets/js/app.js
  assets/styles/profile.scss
  assets/styles/variables.scss
  migrations/Version20210120221943.php
  package.json
  src/Controller/AdminCalendarController.php
  src/Entity/Calendar.php
  src/Form/CalendarType.php
  src/Repository/CalendarRepository.php
  templates/admin/calendar/_delete_form.html.twig
  templates/admin/calendar/_form.html.twig
  templates/admin/calendar/edit.html.twig
  templates/admin/calendar/index.html.twig
  templates/admin/calendar/new.html.twig
  templates/admin/calendar/show.html.twig
  templates/contact/contact.html.twig
  templates/profile/index.html.twig
  yarn.lock
Labels: Reviewed

#229 change walking view
  assets/styles/walking.scss
  templates/walking/index.html.twig
Labels: Reviewed

#231 finished modifiy text gym
  src/Controller/AdminGymController.php
  templates/admin/gym/edit.html.twig
  templates/admin/gym/show.html.twig
  templates/gym/edit.html.twig
  templates/gym/indexAdmin.html.twig
  templates/gym/show.html.twig
Labels: Reviewed

#232 Us71 crud parti delete admin company
  migrations/Version20210121082721.php
  src/Controller/AdminCompanyController.php
  src/Form/CompanyType.php
  templates/admin/company/_delete_form.html.twig
  templates/admin/company/_form.html.twig
  templates/admin/company/edit.html.twig
  templates/admin/company/index.html.twig
  templates/admin/company/new.html.twig
  templates/admin/company/show.html.twig
  templates/company/index.html.twig
Labels: Reviewed

#233 add navbar customer accounts
  templates/admin/customerAccount/index.html.twig
Labels: Reviewed

#235 finished deletion text
  src/Controller/AdminGymController.php
  templates/admin/gym/_delete_form.html.twig
  templates/admin/gym/indexAdmin.html.twig
  templates/gym/_delete_form.html.twig
  templates/gym/indexAdmin.html.twig
Labels: Reviewed

#236 put back index gym
  templates/gym/index.html.twig
Labels: Reviewed

#237 fixture erreur
  src/DataFixtures/CarouselFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/PresentationFixture.php
Labels: Reviewed

#238 fix admin index
  templates/admin/index.html.twig
Labels: Reviewed

#239 Mise en page edit admin company
  src/Controller/AdminCompanyController.php
  src/Entity/Company.php
  templates/admin/company/_form.html.twig
  templates/admin/company/edit.html.twig
Labels: Reviewed

#243 mise en place du crud + modification partie delete admin presentation
  src/Controller/AdminPresentationController.php
  src/Form/PresentationType.php
  templates/admin/presentation/_delete_form.html.twig
  templates/admin/presentation/_form.html.twig
  templates/admin/presentation/edit.html.twig
  templates/admin/presentation/index.html.twig
  templates/admin/presentation/new.html.twig
  templates/admin/presentation/show.html.twig
Labels: Reviewed

#244 Us60 modifier activity
  src/Controller/ActivityController.php
  templates/admin/activity/_form.html.twig
  templates/admin/activity/edit.html.twig
Labels: Reviewed

#245 Us61 supprimer activity
  src/Controller/ActivityController.php
  templates/admin/activity/_delete_form.html.twig
Labels: Reviewed

#246 Us59 view activity admin
  src/Controller/ActivityController.php
  templates/admin/activity/index.html.twig
  templates/admin/activity/show.html.twig
Labels: Reviewed

#247 Fix graphique sur toute la parti admin
  assets/styles/admin.scss
  assets/styles/app.scss
  migrations/Version20210120221943.php
  src/DataFixtures/CarouselFixtures.php
  templates/admin/customerAccount/index.html.twig
  templates/admin/fitness/indexAdmin.html.twig
  templates/admin/gym/indexAdmin.html.twig
  templates/admin/gym/new.html.twig
  templates/admin/home/index_admin.html.twig
  templates/admin/media/_form.html.twig
  templates/admin/media/edit.html.twig
  templates/admin/media/index.html.twig
  templates/admin/media/new.html.twig
  templates/admin/tarif/_delete_form.html.twig
  templates/admin/tarif/_form.html.twig
  templates/admin/tarif/index.html.twig
  templates/admin/tarif/new.html.twig
  templates/admin/walking/_form.html.twig
  templates/admin/walking/index.html.twig
  templates/carousel/_delete_form.html.twig
  templates/carousel/edit.html.twig
  templates/carousel/index.html.twig
  templates/carousel/show.html.twig
  templates/opinion/index.html.twig
Labels: Reviewed

#248 Fixed addflash
  src/Controller/AdminFitnessController.php
  src/Controller/AdminGymController.php
Labels: Reviewed

#250 Mise en place upload image page presentation
  config/packages/vich_uploader.yaml
  src/Controller/AdminPresentationController.php
  src/Entity/Presentation.php
  src/Form/PresentationType.php
  templates/admin/presentation/edit.html.twig
Labels: Reviewed

#253 mise en place partie new admin presentation
  src/Controller/AdminPresentationController.php
  templates/admin/presentation/new.html.twig
Labels: Reviewed

#254 mise a jour de la page
  templates/company/index.html.twig
Labels: Reviewed

#257 Fix navbar
  templates/include/_navbar.html.twig
Labels: Reviewed

#255 Fix lien photo
  assets/styles/admin.scss
  assets/styles/adminWalking.scss
  templates/activity/index.html.twig
  templates/admin/walking/index.html.twig
  templates/home/index.html.twig
  templates/include/_carousel.html.twig
  templates/whoIAm/index.html.twig
Labels: Reviewed

#252 mise en place crud parti edit, mise a jour des nouveax liens
  src/Controller/AdminPresentationController.php
  templates/admin/index.html.twig
  templates/admin/presentation/_form.html.twig
  templates/admin/presentation/edit.html.twig
  templates/includeAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#256 mise en place des images sur la partie admin
  assets/styles/admin.scss
  templates/admin/home/index_admin.html.twig
  templates/carousel/index.html.twig
Labels: Reviewed

#259 refonte graphique tarif
  templates/contact/contact.html.twig
  templates/tarif/index.html.twig
Labels: Reviewed

#260 mise en forme + petit fix qui suis je lien
  src/Controller/AdminPresentationController.php
  templates/admin/presentation/index.html.twig
  templates/whoIAm/index.html.twig
Labels: Reviewed

#262 securisation/admin plus remise admin dans le bon dossier
  src/Controller/AdminCarouselController.php
  src/Controller/OpinionController.php
  templates/admin/carousel/_delete_form.html.twig
  templates/admin/carousel/_form.html.twig
  templates/admin/carousel/edit.html.twig
  templates/admin/carousel/index.html.twig
  templates/admin/carousel/new.html.twig
  templates/admin/opinion/_delete_form.html.twig
  templates/admin/opinion/_form.html.twig
  templates/admin/opinion/edit.html.twig
  templates/admin/opinion/index.html.twig
  templates/admin/opinion/new.html.twig
Labels: Reviewed

#261 Us81 mise en place entity contact
  src/Controller/ContactController.php
  src/DataFixtures/ContactFixtures.php
  src/Entity/Contact.php
  src/Repository/ContactRepository.php
  templates/contact/contact.html.twig
Labels: Reviewed

#271 created new regulation
  src/Controller/RegulationController.php
  src/Entity/Regulation.php
  src/Form/RegulationType.php
  src/Repository/RegulationRepository.php
  templates/admin/regulation/_delete_form.html.twig
  templates/admin/regulation/_form.html.twig
  templates/admin/regulation/edit.html.twig
  templates/admin/regulation/new.html.twig
  templates/admin/regulation/show.html.twig
  templates/regulation/index.html.twig
Labels: Reviewed

#272 fix partie admin apres modification de vendredi
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  templates/admin/activity/_form.html.twig
  templates/admin/activity/indexAdmin.html.twig
Labels: Reviewed

#276 change entity calendar + index + form
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  src/Entity/Calendar.php
  src/Form/CalendarType.php
  symfony.lock
  templates/admin/calendar/index.html.twig
  templates/admin/calendar/new.html.twig
Labels: Reviewed

#277 S07 us86 add planning view walking page
  migrations/Version20210125113218.php
  src/Controller/WalkingController.php
  src/Entity/Walking.php
  templates/walking/calendar.html.twig
  templates/walking/index.html.twig
Labels: Change Requested

#273 Us85 cration entity cgv
  assets/images/dep57.xls
  assets/images/logoCouleur.jpg
  assets/images/salleSportContact.jpg
  migrations/Version20210125152304.php
  src/Controller/CgvController.php
  src/DataFixtures/CvgFixtures.php
  src/Entity/Cgv.php
  src/Repository/CgvRepository.php
  templates/cgv/index.html.twig
  templates/include/_footer.html.twig
Labels: Reviewed

#274 S07 us82 reset password
  assets/styles/security.scss
  composer.lock
  config/packages/reset_password.yaml
  migrations/Version20210125093610.php
  phpstan.neon
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/RegistrationFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  webpack.config.js
Labels: Reviewed

#279 Us68 calendar
  templates/admin/calendar/_form.html.twig
  templates/admin/calendar/index.html.twig
  templates/admin/calendar/new.html.twig
Labels: Reviewed

#280 US90 modification RGPD
  src/Controller/RegulationController.php
  templates/admin/regulation/edit.html.twig
Labels: Reviewed

#281 Us91 supprimer RGPD
  src/Controller/RegulationController.php
  templates/admin/regulation/_delete_form.html.twig
Labels: Reviewed

#283 view admin rgpd
  src/Controller/RegulationController.php
  templates/admin/regulation/indexAdmin.html.twig
Labels: Reviewed

#284 fix general
  assets/styles/gym.scss
  src/Form/ContactHomeType.php
  templates/activity/index.html.twig
  templates/company/index.html.twig
  templates/fitness/index.html.twig
  templates/gym/index.html.twig
  templates/home/index.html.twig
  templates/walking/index.html.twig
Labels: Reviewed

#285 Us 93view client rgpd
  src/Controller/RegulationController.php
  src/DataFixtures/RegulationFixtures.php
  templates/include/_footer.html.twig
  templates/regulation/index.html.twig
Labels: Reviewed

#286 add pdf to the entity walking for the admin crud
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210125170836.php
  src/Controller/AdminWalkingController.php
  src/Entity/Walking.php
  src/Form/WalkingType.php
  templates/admin/walking/_form.html.twig
  templates/admin/walking/index.html.twig
Labels: Reviewed

#278 mise en place crud plus edit
  migrations/Version20210125093610.php
  migrations/Version20210125113218.php
  migrations/Version20210125152304.php
  src/Controller/AdminContactController.php
  src/DataFixtures/CgvFixtures.php
  src/Form/ContactType.php
  templates/admin/contact/_delete_form.html.twig
  templates/admin/contact/_form.html.twig
  templates/admin/contact/edit.html.twig
  templates/admin/contact/index.html.twig
  templates/admin/contact/new.html.twig
Labels: Reviewed

#282 ajoute d'une table
  src/DataFixtures/TariffFixtures.php
  src/Entity/Tariff.php
  templates/tarif/index.html.twig
Labels: Reviewed

#294 fix padding and responsive
  templates/reset_password/check_email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
Labels: Reviewed

#295 fix boostsrap plus reglage erreur
  config/packages/twig.yaml
  src/Controller/AdminActivityController.php
  src/Controller/RegulationController.php
  templates/admin/activity/_delete_form.html.twig
  templates/admin/activity/_form.html.twig
  templates/admin/activity/indexAdmin.html.twig
  templates/admin/activity/new.html.twig
  templates/admin/activity/show.html.twig
  templates/admin/calendar/_delete_form.html.twig
  templates/admin/calendar/_form.html.twig
  templates/admin/carousel/edit.html.twig
  templates/admin/carousel/new.html.twig
  templates/admin/company/_form.html.twig
  templates/admin/company/show.html.twig
  templates/admin/fitness/_form.html.twig
  templates/admin/gym/_form.html.twig
  templates/admin/home/_form.html.twig
  templates/admin/home/edit.html.twig
  templates/admin/index.html.twig
  templates/admin/media/_form.html.twig
  templates/admin/media/edit.html.twig
  templates/admin/media/show.html.twig
  templates/admin/opinion/edit.html.twig
  templates/admin/opinion/new.html.twig
  templates/admin/presentation/_form.html.twig
  templates/admin/presentation/show.html.twig
  templates/admin/regulation/_form.html.twig
  templates/admin/regulation/show.html.twig
  templates/admin/tarif/edit.html.twig
  templates/admin/tarif/new.html.twig
  templates/admin/walking/_form.html.twig
  templates/admin/walking/new.html.twig
  templates/contact/contact.html.twig
  templates/home/index.html.twig
  templates/regulation/index.html.twig
Labels: Reviewed

#296 delete dossier
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Reviewed

#297 fix view pictures walking
  assets/styles/walking.scss
  migrations/Version20210126102205.php
  src/Entity/Walking.php
  src/Form/WalkingType.php
  templates/walking/index.html.twig
Labels: Reviewed

#298 Fix bug activity
  src/Controller/AdminActivityController.php
  templates/admin/activity/show.html.twig
  templates/admin/index.html.twig
Labels: Reviewed

#302 fix email button walking page
  templates/walking/index.html.twig
Labels: Reviewed

#303 Mise en place index admin contact
  src/Controller/AdminContactController.php
  templates/admin/contact/index.html.twig
  templates/admin/contact/new.html.twig
Labels: Reviewed

#304 ajout des nouveaux lien
  assets/images/contact.png
  assets/images/mentionsLegales.png
  composer.lock
  templates/admin/index.html.twig
  templates/includeAdmin/_navbarAdmin.html.twig
Labels: Reviewed

#306 finish delete images
  assets/images/IMG_4510-compressed.jpg
  assets/images/LosingWeight.jpg
  assets/images/backgroundFitness.jpg
  assets/images/fondSectionSport.jpg
  assets/images/nordic_walking.jpg
  assets/images/nordic_walking_place_holder_1.jpg
  assets/images/nordic_walking_place_holder_2.jpg
  assets/images/nordic_walking_place_holder_3.jpg
  assets/images/nordic_walking_place_holder_4.jpg
  assets/images/overlay.jpg
  assets/images/placeholder150.png
  assets/images/remiseEnForme.jpg
  assets/images/remise_en_forme_carousel.jpg
  assets/images/remise_en_forme_carousel_2.jpg
  assets/images/sportAdapte.jpg
  assets/images/who.jpg
Labels: Reviewed

#300 Us83 crud and edit cgv
  migrations/Version20210125170836.php
  src/Controller/AdminCgvController.php
  src/Form/CgvType.php
  templates/admin/cgv/_delete_form.html.twig
  templates/admin/cgv/_form.html.twig
  templates/admin/cgv/edit.html.twig
  templates/admin/cgv/index.html.twig
  templates/admin/cgv/new.html.twig
  templates/admin/cgv/show.html.twig
Labels: Reviewed

#301 Us80 crud delete admin contact
  src/Controller/AdminContactController.php
  templates/admin/contact/_delete_form.html.twig
  templates/admin/contact/_form.html.twig
Labels: Reviewed

#307 traduction
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  src/Controller/AdminCalendarController.php
  src/Controller/AdminCarouselController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminWalkingController.php
  src/Controller/CustomerController.php
  src/Controller/OpinionController.php
  src/Controller/ProfileController.php
  src/Controller/RegistrationController.php
  src/Controller/RegulationController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Controller/WalkingController.php
  src/Controller/WhoIAmController.php
Labels: Reviewed

#293 delete
  src/Controller/AdminCalendarController.php
  templates/admin/calendar/_delete_form.html.twig
Labels: Reviewed

#308 fix flash messages
  src/Controller/AdminActivityController.php
  src/Controller/AdminFitnessController.php
  src/Controller/AdminGymController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminWalkingController.php
Labels: Reviewed

#309 Mise en place index admin cgv
  assets/images/cvg.png
  assets/styles/barNav.scss
  src/Controller/AdminCgvController.php
  src/Form/CgvType.php
  templates/admin/cgv/_delete_form.html.twig
  templates/admin/cgv/_form.html.twig
  templates/admin/cgv/edit.html.twig
  templates/admin/cgv/index.html.twig
  templates/admin/cgv/new.html.twig
  templates/admin/cgv/show.html.twig
Labels: Reviewed

#311 mise en place graphisme
  templates/admin/calendar/_form.html.twig
  templates/admin/calendar/edit.html.twig
  templates/admin/calendar/index.html.twig
  templates/admin/calendar/show.html.twig
Labels: Reviewed

#313 fix controllers
  migrations/Version20210126102205.php
  src/Controller/AdminOpinionController.php
  src/Controller/AdminWalkingController.php
  templates/admin/activity/show.html.twig
  templates/walking/index.html.twig
Labels: Reviewed

#316 fix use
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  src/Controller/AdminController.php
  src/Controller/AdminFitnessController.php
  src/Controller/AdminGymController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminWalkingController.php
  src/Controller/CgvController.php
  src/Controller/CompanyController.php
  src/Controller/FitnessController.php
  src/Controller/GymController.php
  src/Controller/HomeController.php
  src/Controller/ProfileController.php
  src/Controller/RegulationController.php
  src/Controller/TariffController.php
  src/Controller/WalkingController.php
Labels: Reviewed

#318 Vue carte calendrier
  composer.json
  composer.lock
  migrations/Version20210126142739.php
  src/Controller/AdminCalendarController.php
  src/Controller/ProfileController.php
  src/Entity/Calendar.php
  src/Entity/User.php
  symfony.lock
  templates/admin/calendar/show.html.twig
  templates/profile/index.html.twig
Labels: Reviewed

#319 carte fini
  composer.lock
  templates/admin/calendar/show.html.twig
  templates/profile/index.html.twig
Labels: Reviewed

#320 Fix uploads
  composer.lock
  config/packages/vich_uploader.yaml
  config/services.yaml
  templates/admin/home/index_admin.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#321 Show calendar
  src/Controller/AdminCalendarController.php
  src/Controller/ProfileController.php
  templates/admin/calendar/index.html.twig
  templates/admin/calendar/show.html.twig
  templates/profile/index.html.twig
Labels: Reviewed

#323 Fix tableau profile
  templates/profile/show.html.twig
Labels: Reviewed

#324 add button admin contact
  templates/admin/contact/index.html.twig
Labels: Reviewed

#326 add padding footer
  templates/include/_footer.html.twig
Labels: Reviewed

#327 finished Readme
  README.md
Labels: Reviewed

#329 add 401 page
  templates/bundles/TwigBundle/Exception/error401.html.twig
Labels: Reviewed

#328 Fix label
  src/Form/ActivityType.php
  src/Form/CalendarType.php
  src/Form/CarouselType.php
  src/Form/CgvType.php
  src/Form/CompanyType.php
  src/Form/ContactHomeType.php
  src/Form/ContactType.php
  src/Form/FitnessType.php
  src/Form/GymType.php
  src/Form/HomeType.php
  src/Form/MediaType.php
  src/Form/OpinionType.php
  src/Form/PresentationType.php
  src/Form/TariffType.php
  src/Form/UserType.php
  src/Form/WalkingType.php
  templates/admin/calendar/_form.html.twig
Labels: Reviewed

#330 Dev to master
  README.md
  composer.json
  composer.lock
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210126142739.php
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  src/Controller/AdminCalendarController.php
  src/Controller/AdminController.php
  src/Controller/AdminFitnessController.php
  src/Controller/AdminGymController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminWalkingController.php
  src/Controller/CgvController.php
  src/Controller/CompanyController.php
  src/Controller/FitnessController.php
  src/Controller/GymController.php
  src/Controller/HomeController.php
  src/Controller/ProfileController.php
  src/Controller/RegulationController.php
  src/Controller/TariffController.php
  src/Controller/WalkingController.php
  src/Entity/Calendar.php
  src/Entity/User.php
  src/Form/ActivityType.php
  src/Form/CalendarType.php
  src/Form/CarouselType.php
  src/Form/CgvType.php
  src/Form/CompanyType.php
  src/Form/ContactHomeType.php
  src/Form/ContactType.php
  src/Form/FitnessType.php
  src/Form/GymType.php
  src/Form/HomeType.php
  src/Form/MediaType.php
  src/Form/OpinionType.php
  src/Form/PresentationType.php
  src/Form/TariffType.php
  src/Form/UserType.php
  src/Form/WalkingType.php
  symfony.lock
  templates/admin/calendar/_form.html.twig
  templates/admin/calendar/index.html.twig
  templates/admin/calendar/show.html.twig
  templates/admin/contact/index.html.twig
  templates/admin/home/index_admin.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/home/index.html.twig
  templates/include/_footer.html.twig
  templates/profile/index.html.twig
  templates/profile/show.html.twig
Labels: Reviewed

#365 Fix issue 344
  src/DataFixtures/WalkingFixtures.php
Labels: Reviewed

#368 Fix general
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/barNav.scss
  migrations/Version20210126142739.php
  migrations/Version20210127151725.php
  src/Controller/AdminGymController.php
  src/Entity/Carousel.php
  src/Entity/Home.php
  src/Entity/Presentation.php
  src/Entity/Walking.php
  src/Form/TariffType.php
  templates/admin/activity/indexAdmin.html.twig
  templates/admin/cgv/index.html.twig
  templates/admin/company/index.html.twig
  templates/admin/contact/index.html.twig
  templates/admin/customerAccount/index.html.twig
  templates/admin/fitness/indexAdmin.html.twig
  templates/admin/gym/indexAdmin.html.twig
  templates/admin/media/index.html.twig
  templates/admin/opinion/index.html.twig
  templates/admin/presentation/index.html.twig
  templates/admin/regulation/indexAdmin.html.twig
  templates/admin/tarif/index.html.twig
  templates/admin/walking/index.html.twig
  templates/include/_navbar.html.twig
  webpack.config.js
Labels: Reviewed

#369 fixed Readme#335
  README.md
Labels: Reviewed

#370 Fixe mail
  templates/contact/contactConfirmation.html.twig
Labels: Reviewed
